# <center>Numpy快速上手指南 --- 基础篇</center>

这篇文档是参加**「DATA TRAIN|金融行业数据算法练习赛」**的前期学习素材。

文档内容转载整理自知乎文章 [Nupmy的详细教程](https://zhuanlan.zhihu.com/p/24988491) 及Scipy官网 [Numpy Quickstart Tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)，**将其中的代码在K-Lab上实现Python3下的复盘**，分为**基础篇（本文）**和进阶篇。欢迎点击右上角**「Fork」**按钮动手调试学习Python代码

转载本文请联系 [科赛网](https//:www.kesci.com) 及 [知乎文章原作者](https://www.zhihu.com/people/wen-yi-yang-81/activities) 取得授权，**科赛网**是聚合数据人才和行业问题的在线社区，率先打造国内首款K-Lab 在线数据分析协作平台，为数据工作者的学习与工作带来全新的体验。

    
** 内容索引**
* 1.概览
* 2.创建数组
* 3.打印数组
* 4.基本运算
* 5.通用函数
* 6.形状操作
* 7.函数和方法```method```总览

## 1. 概览
Numpy的主要对象是同种元素的多维数组。这是一个所有的元素都是一种类型、通过一个正整数元组索引的元素表格(通常是元素是数字)。在Numpy中维度(dimensions)叫做轴(axes)，轴的个数叫做秩(rank)。

例如，在3D空间一个点的坐标[1, 2, 3]是一个秩为1的数组，因为它只有一个轴。那个轴长度为3.又例如，在以下例子中，数组的秩为2(它有两个维度).第一个维度长度为2,第二个维度长度为3.

[[ 1., 0., 0.],
 [ 0., 1., 2.]]

Numpy的数组类被称作```ndarray```。通常被称作数组。注意```numpy.array```和标准```Python```库类```array.array```并不相同，后者只处理一维数组和提供少量功能。更多重要```ndarray```对象属性有：

* ```ndarray.ndim```

数组轴的个数，在python的世界中，轴的个数被称作秩

* ```ndarray.shape```

数组的维度。这是一个指示数组在每个维度上大小的整数元组。例如一个```n```排```m```列的矩阵，它的```shape```属性将是(2,3),这个元组的长度显然是秩，即维度或者```ndim```属性

* ```ndarray.size```

数组元素的总个数，等于```shape```属性中元组元素的乘积。

* ```ndarray.dtype```

一个用来描述数组中元素类型的对象，可以通过创造或指定```dtype```使用标准```Python```类型。另外Numpy提供它自己的数据类型。

* ```ndarray.itemsize```

数组中每个元素的字节大小。例如，一个元素类型为```float64```的数组```itemsiz```属性值为8(=64/8),又如，一个元素类型为```complex32```的数组```item```属性为```4(=32/8)```.

* ```ndarray.data```

包含实际数组元素的缓冲区，通常我们不需要使用这个属性，因为我们总是通过索引来使用数组中的元素。

#### 例子

In [3]:
from numpy  import *
a = arange(15).reshape(3, 5)
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim 

2

In [4]:
a.dtype.name

'int64'

In [4]:
a.itemsize  

4

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = array([6, 7, 8])
b 

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

## 2. 创建数组

有好几种创建数组的方法。    
例如，你可以使用```array```函数从常规的```Python```列表和元组创造数组。所创建的数组类型由原序列中的元素类型推导而来。

In [10]:
from numpy  import *
a = array( [2,3,4] )
a

array([2, 3, 4])

In [11]:
a.dtype 

dtype('int64')

In [12]:
b = array([1.2, 3.5, 5.1])
b.dtype   # 一个常见的错误包括用多个数值参数调用 array 而不是提供一个由数值组成的列表作为一个参数。

dtype('float64')

**正确创建方式与错误创建方式对比**
```python
a = array(1,2,3,4)    # 错误的创建方式
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-194-501541f17041> in <module>()
----> 1 a = array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted
```

```python
a = array([1,2,3,4])  # 正确的创建方式
```

数组将序列包含序列转化成二维的数组，序列包含序列包含序列转化成三维数组等等。

In [13]:
b = array([(1.5,2,3),(4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

数组类型可以在创建时显示指定

In [14]:
c = array([[1,2],[3,4]], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

通常，数组的元素开始都是未知的，但是它的大小已知。因此，Numpy提供了一些使用占位符创建数组的函数。这最小化了扩展数组的需要和高昂的运算代价。

函数```function```创建一个全是0的数组，函数```ones```创建一个全1的数组，函数```empty```创建一个内容随机并且依赖与内存状态的数组。*默认创建的数组类型```(dtype)```都是```float64```*。

In [15]:
zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
ones((2,3,4),dtype=int16)                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

为了创建一个数列，Numpy提供一个类似```arange```的函数返回数组而不是列表:

In [18]:
arange(10,30,5)

array([10, 15, 20, 25])

In [19]:
arange( 0, 2, 0.3 )                 # it accepts float arguments

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

当arange使用浮点数参数时，由于有限的浮点数精度，通常无法预测获得的元素个数。因此，最好使用函数linspace去接收我们想要的元素个数来代替用range来指定步长。

其它函数array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, rand, randn, fromfunction, fromfile参考：NumPy示例

## 3. 打印数组

当你打印一个数组，NumPy以类似嵌套列表的形式显示它，但是呈以下布局：

* 最后的轴从左到右打印
* 次后的轴从顶向下打印
* 剩下的轴从顶向下打印，每个切片通过一个空行与下一个隔开
* 一维数组被打印成行，二维数组成矩阵，三维数组成矩阵列表。

In [20]:
a = arange(6)                         # 1d array
print (a)  

[0 1 2 3 4 5]


In [21]:
b = arange(12).reshape(4,3)           # 2d array
print (b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
c = arange(24).reshape(2,3,4)         # 3d array
print (c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


查看形状操作一节获得有关```reshape```的更多细节

**如果一个数组用来打印太大了，NumPy自动省略中间部分而只打印角落**

In [23]:
print (arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [24]:
print (arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


禁用NumPy的这种行为并强制打印整个数组，你可以设置printoptions参数来更改打印选项。
```python
set_printoptions(threshold='nan')
```

## 4. 基本运算

数组的算术运算是按元素的。新的数组被创建并且被结果填充

In [25]:
from numpy import *
a = array([20,30,40,50])
b = arange(4)
b

array([0, 1, 2, 3])

In [26]:
c = a-b
c

array([20, 29, 38, 47])

In [27]:
b**2

array([0, 1, 4, 9])

In [28]:
10*sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [29]:
a<35

array([ True,  True, False, False], dtype=bool)

不像许多矩阵语言，NumPy中的乘法运算符*指示按元素计算，矩阵乘法可以使用dot函数或创建矩阵对象实现(参见教程中的矩阵章节)

In [30]:
A = array( [[1,1],
            [0,1]] )
B = array( [[2,0],
            [3,4]] )

A*B     # elementwise product

array([[2, 0],
       [0, 4]])

In [31]:
dot(A,B)                    # matrix product

array([[5, 4],
       [3, 4]])

有些操作符像+=和*=被用来更改已存在数组而不创建一个新的数组。

In [32]:
a = ones((2,3), dtype=int)
b = random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [33]:
b += a
b

array([[ 3.04610006,  3.25068416,  3.39458014],
       [ 3.34956036,  3.30907687,  3.05677917]])

**错误的方式**
```python
a += b                                  # b is converted to integer type
a
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-219-2b1a0b731705> in <module>()
----> 1 a += b                                  # b is converted to integer type
      2 a

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

当运算的是不同类型的数组时，结果数组和更普遍和精确的已知，这种行为叫做 ```upcast```。

In [34]:
a = ones(3, dtype=int32)
b = linspace(0,pi,3)
b.dtype.name

'float64'

In [35]:
c = a+b
c   

array([ 1.        ,  2.57079633,  4.14159265])

In [36]:
c.dtype.name

'float64'

In [37]:
d = exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [38]:
d.dtype.name # 许多非数组运算，如计算数组所有元素之和，被作为ndarray类的方法实现

'complex128'

In [39]:
a = random.random((2,3))
a

array([[ 0.58120218,  0.65134515,  0.86005124],
       [ 0.47042799,  0.59048742,  0.84672098]])

In [40]:
a.sum() 

4.0002349566329114

In [41]:
a.min() 

0.47042798669229968

In [42]:
a.max() 

0.86005123623089985

这些运算默认应用到数组好像它就是一个数字组成的列表，无关数组的形状。然而，指定```axis```参数你可以吧运算应用到数组指定的轴上：

In [43]:
b = arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [45]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [46]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## 5. 通用函数 ```ufunc```

Numpy提供常见的数学函数如 ```sin```, ```cos``` 和 ```exp```。在Numpy中，这些叫作**通用函数** ```ufunc```。在Numpy里这些函数作用按数组的元素运算，产生一个数组作为输出。

In [47]:
B = arange(3)
B

array([0, 1, 2])

In [48]:
exp(B) 

array([ 1.        ,  2.71828183,  7.3890561 ])

In [49]:
sqrt(B) 

array([ 0.        ,  1.        ,  1.41421356])

In [50]:
C = array([2., -1., 4.])
add(B, C)  

array([ 2.,  0.,  6.])

更多函数   
```python 
all, alltrue, any, apply along axis, argmax, argmin, argsort, average,     
bincount, ceil, clip, conj, conjugate, corrcoef, cov, cross, cumprod, cumsum, 
diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, 
nonzero, outer, prod, re, round, sometrue, sort, std, sum, trace, transpose, 
var, vdot, vectorize, where
```     

### 索引，切片和迭代

一维数组可以被索引、切片和迭代，就像列表和其它Python序列。

In [51]:
a = arange(10)**3
a  

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [52]:
a[2] 

8

In [53]:
a[2:5]

array([ 8, 27, 64])

In [54]:
a[:6:2] = -1000  # equivalent to a[0:6:2] = -1000; 
a                # from start to position 6, exclusive, set every 2nd element to -1000

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [55]:
a[ : :-1]       # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [97]:
for i in a:
    print (i**(1/3.),end=",")

[ 0.          2.15443469  2.15443469  1.44224957],[ 10.72601467   2.15443469   2.15443469   1.91293118],[ 2.          2.15443469  2.15443469  2.22398009],

多维数组可以每个轴有一个索引。这些索引由一个逗号分割的元组给出。

In [57]:
def f(x,y):
    return 10*x+y
b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [58]:
b[2,3] 

23

In [59]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [60]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [61]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

当少于轴数的索引被提供时，确失的索引被认为是整个切片：

In [62]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

b[i]中括号中的表达式被当作i和一系列:，来代表剩下的轴。NumPy也允许你使用“点”像b[i,...]。

点(…)代表许多产生一个完整的索引元组必要的分号。如果x是秩为5的数组(即它有5个轴)，那么:

* ```x[1,2,…]``` 等同于 ```x[1,2,:,:,:]```
* ```x[…,3]``` 等同于 ```x[:,:,:,:,3]```
* ```x[4,…,5,:]``` 等同于 ```x[4,:,:,5,:]```    

**如下所示**
```python
# c = array( [ [[  0,  1,  2],  # a 3D array (two stacked 2D arrays) ... [ 10, 12, 13]]... 
# [[100,101,102], ... [110,112,113]] ] ) 
# c.shape (2, 2, 3) 
# c[1,...]    # same as c[1,:,:] or c[1] array([[100, 101, 102], [110, 112, 113]]) 
# c[...,2]      # same as c[:,:,2] array([[  2,  13], [102, 113]]) 
```

迭代多维数组是就第一个轴而言的

In [63]:
for row in b:
    print (row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


然而，如果一个人想对每个数组中元素进行运算，我们可以使用flat属性，该属性是数组元素的一个迭代器:

In [64]:
for element in b.flat:
    print (element,end=",")   #

0,1,2,3,10,11,12,13,20,21,22,23,30,31,32,33,40,41,42,43,

更多```newaxis```, ```ndenumerate```, ```indices```, ```index exp``` 参考Numpy示例

## 6. 形状操作
### 更改数组的形状
一个数组的形状由它每个轴上的元素个数给出：

In [65]:
a = floor(10*random.random((3,4)))
a

array([[ 6.,  7.,  4.,  3.],
       [ 0.,  0.,  2.,  6.],
       [ 7.,  7.,  8.,  6.]])

In [66]:
a.shape 

(3, 4)

一个数组的形状可以被多种命令修改：

In [67]:
a.ravel() # flatten the array

array([ 6.,  7.,  4.,  3.,  0.,  0.,  2.,  6.,  7.,  7.,  8.,  6.])

In [68]:
a.shape = (6, 2)
a.transpose()

array([[ 6.,  4.,  0.,  2.,  7.,  8.],
       [ 7.,  3.,  0.,  6.,  7.,  6.]])

由```ravel()```展平的数组元素的顺序通常是 *C风格* 的，就是说，**最右边的索引变化得最快**，所以元素```a[0,0]```之后是```a[0,1]```。如果数组被改变形状(```reshape```)成其它形状，数组仍然是 *C风格* 的。Numpy通常创建一个以这个顺序保存数据的数组，所以```ravel()```将总是不需要复制它的参数。但是如果数组是通过切片其它数组或有不同寻常的选项时，它可能需要被复制。函数```reshape()```和```ravel()```还可以被同过一些可选参数构建成 *FORTRAN风格* 的数组，即最左边的索引变化最快。

```reshape```函数改变参数形状并返回它，而```resize```函数改变数组自身。

In [69]:
a

array([[ 6.,  7.],
       [ 4.,  3.],
       [ 0.,  0.],
       [ 2.,  6.],
       [ 7.,  7.],
       [ 8.,  6.]])

In [70]:
a.resize((2,6))
a

array([[ 6.,  7.,  4.,  3.,  0.,  0.],
       [ 2.,  6.,  7.,  7.,  8.,  6.]])

如果在改变形状操作中一个维度被给做-1，其维度将自动被计算

更多 ```shape```, ```reshape```, ```resize```, ```ravel``` 参考Numpy示例

### 组合(stack)不同的数组

几种方法可以沿不同轴将数组堆叠在一起：

In [71]:
a = floor(10*random.random((2,2)))
a

array([[ 1.,  5.],
       [ 6.,  7.]])

In [72]:
b = floor(10*random.random((2,2)))
b

array([[ 5.,  5.],
       [ 4.,  5.]])

In [73]:
vstack((a,b))

array([[ 1.,  5.],
       [ 6.,  7.],
       [ 5.,  5.],
       [ 4.,  5.]])

In [74]:
hstack((a,b))

array([[ 1.,  5.,  5.,  5.],
       [ 6.,  7.,  4.,  5.]])

函数```column_stack```以列将一维数组合成二维数组，它等同与```vstack```对一维数组。

In [75]:
column_stack((a,b))   # With 2D arrays

array([[ 1.,  5.,  5.,  5.],
       [ 6.,  7.,  4.,  5.]])

In [76]:
a=array([4.,2.])
b=array([2.,8.])
a[:,newaxis]  # This allows to have a 2D columns vector

array([[ 4.],
       [ 2.]])

In [77]:
column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [78]:
vstack((a[:,newaxis],b[:,newaxis])) # The behavior of vstack is different

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

```row_stack```函数，另一方面，将一维数组以行组合成二维数组。

对那些维度比二维更高的数组，```hstack```沿着第二个轴组合，```vstack```沿着第一个轴组合,```concatenate```允许可选参数给出组合时沿着的轴。

在复杂情况下，```r_[]```和```c_[]```对创建沿着一个方向组合的数很有用，它们允许范围符号(“:”):

In [79]:
r_[1:4,0,4]   

array([1, 2, 3, 0, 4])

当使用数组作为参数时，```r_```和```c_```的默认行为和```vstack```和```hstack```很像，但是允许可选的参数给出组合所沿着的轴的代号。

更多函数```hstack```, ```vstack```, ```column_stack```, ```row_stack```, ```concatenate```, ```c_```, ```r_``` 参见Numpy示例.


### 将一个数组分割(split)成几个小数组

使用```hsplit```你能将数组沿着它的水平轴分割，或者指定返回相同形状数组的个数，或者指定在哪些列后发生分割:

In [80]:
a = floor(10*random.random((2,12)))
a

array([[ 3.,  7.,  0.,  6.,  0.,  6.,  8.,  5.,  8.,  2.,  7.,  1.],
       [ 7.,  7.,  2.,  3.,  4.,  8.,  8.,  5.,  2.,  5.,  5.,  4.]])

In [81]:
hsplit(a,3)   # Split a into 3

[array([[ 3.,  7.,  0.,  6.],
        [ 7.,  7.,  2.,  3.]]), array([[ 0.,  6.,  8.,  5.],
        [ 4.,  8.,  8.,  5.]]), array([[ 8.,  2.,  7.,  1.],
        [ 2.,  5.,  5.,  4.]])]

In [82]:
hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[ 3.,  7.,  0.],
        [ 7.,  7.,  2.]]), array([[ 6.],
        [ 3.]]), array([[ 0.,  6.,  8.,  5.,  8.,  2.,  7.,  1.],
        [ 4.,  8.,  8.,  5.,  2.,  5.,  5.,  4.]])]

```vsplit```沿着纵向的轴分割，```array split```允许指定沿哪个轴分割。

### 复制和视图
当运算和处理数组时，它们的数据有时被拷贝到新的数组有时不是。这通常是新手的困惑之源。这有三种情况:
* **完全不拷贝**    
简单的赋值不拷贝数组对象或它们的数据。

In [83]:
a = arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [84]:
b.shape = 3,4    # changes the shape of a
a.shape 

(3, 4)

Python 传递不定对象作为参考，所以函数调用不拷贝数组。

In [85]:
def f(x):
    print (id(x))

In [86]:
id(a)                           # id is a unique identifier of an object

4538177536

In [87]:
f(a)

4538177536


* **视图(view)和浅复制**    
不同的数组对象分享同一个数据。视图方法创造一个新的数组对象指向同一数据。

In [88]:
c = a.view()
c is a 

False

In [89]:
c.base is a                        # c is a view of the data owned by a

True

In [90]:
c.flags.owndata

False

In [91]:
c.shape = 2,6                      # a's shape doesn't change
a.shape 

(3, 4)

In [92]:
c[0,4] = 1234                      # a's data changesa
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

切片数组返回它的一个视图：

In [93]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

* **深复制**   
这个方法完全复制数组和它的数据

In [94]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [95]:
d.base is a                           # d doesn't share anything with a

False

In [96]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## 7. 函数和方法```method```总览
这是个Numpy函数和方法分类排列目录。这些名字链接到Numpy示例,你可以看到这些函数起作用
### 创建数组
```python
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, 
linspace, logspace, mgrid, ogrid, ones, ones_like, r , zeros, zeros_like 
```
### 转化
```python
astype, atleast 1d, atleast 2d, atleast 3d, mat 
```
### 操作
```python
array split, column stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, item, 
newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack 
```
### 询问
```python
all, any, nonzero, where 
```
### 排序
```python
argmax, argmin, argsort, max, min, ptp, searchsorted, sort 
```
### 运算
```python
choose, compress, cumprod, cumsum, inner, fill, imag, prod, put, putmask, real, sum 
```
### 基本统计
```python
cov, mean, std, var 
```
### 基本线性代数
```python
cross, dot, outer, svd, vdot
```